### ISSUE TITLE
Display hours as a number, not a float

### ISSUE THREAD

**Issue by alexesprit** [ericm/vscode-github-status#5]
Using a float to display hours (e.g. "3.08 hours" which is actually 3 hours and 5 minutes) looks weird. This could be resolved by using either by displaying minutes as well ("3 hours 5 minutes") or by displaying hours as a number ("3 hours"). I find the last option is better for me, as it's more compact, and minutes don't have many value in this case.

What do you think?

**Comment by ericm** [comment]
Yeah it should probs display that way

**Comment by alexesprit** [comment]
@ericm Thanks! Now it's perfect! Closing this one.

P.S. "Close" or "Closes" should be used instead to close issues automatically. :)
